<?php

namespace PrestaShop\Module\ProductVideoLoops\Entity;

/**
 * Example object model for module custom product fields
 */
final class CustomProduct extends \ObjectModel
{
    /**
     * @var int
     */
    public $id;

    /**
     * @var string
     */
    public $filename = '';

    /**
     * @var string
     */
    public $date_add;

    /**
     * @var string
     */
    public $date_upd;

    /**
     * @var bool forces the id to be set before saving object (because we don't need autogenerated id for this model)
     */
    public $force_id = true;

    public static $definition = [
        'table' => 'productvideoloops',
        'primary' => 'id',
        'fields' => [
            'filename' => ['type' => self::TYPE_STRING],
            'date_add' => ['type' => self::TYPE_DATE, 'validate' => 'isDate'],
            'date_upd' => ['type' => self::TYPE_DATE, 'validate' => 'isDate'],
        ],
    ];
}
