<?php

namespace PrestaShop\Module\ProductVideoLoops\Entity;

/**
 * Object model for product video combination fields
 */
final class ProductVideoCombination extends \ObjectModel
{
    /**
     * @var int
     */
    public $id_product;

    /**
     * @var string
     */
    public $filename = '';

    /**
     * @var bool
     */
    public $cover;

    /**
     * @var int
     */
    public $position;

    /**
     * @var string
     */
    public $date_add;

    /**
     * @var string
     */
    public $date_upd;

    /**
     * @var bool forces the id to be set before saving object (because we don't need autogenerated id for this model)
     */
    public $force_id = true;

    public static $definition = [
        'table' => 'productvideoloops',
        'primary' => 'id_product',
        'fields' => [
            'filename' => ['type' => self::TYPE_STRING, 'validate' => 'isString'],
            'cover' => ['type' => self::TYPE_BOOL, 'validate' => 'isBool'],
            'position' => ['type' => self::TYPE_INT, 'validate' => 'isInt'],
            'date_add' => ['type' => self::TYPE_DATE, 'validate' => 'isDate'],
            'date_upd' => ['type' => self::TYPE_DATE, 'validate' => 'isDate'],
        ],
    ];
}
