services:
    slugger:
        class: Symfony\Component\String\Slugger\AsciiSlugger

    #Form modifiers
    PrestaShop\Module\ProductVideoLoops\Form\Modifier\ProductFormModifier:
        class: PrestaShop\Module\ProductVideoLoops\Form\Modifier\ProductFormModifier
        public: true
        autowire: true
        arguments:
            $formBuilderModifier: '@form.form_builder_modifier'

    #CQRS
    PrestaShop\Module\ProductVideoLoops\CQRS\CommandHandler\AddProductVideoCommandHandler:
        class: PrestaShop\Module\ProductVideoLoops\CQRS\CommandHandler\AddProductVideoCommandHandler
        arguments:
            - '@PrestaShop\Module\ProductVideoLoops\Service\VideoManagementService'
        tags:
            - name: tactician.handler
              command: PrestaShop\Module\ProductVideoLoops\CQRS\Command\AddProductVideoCommand

    PrestaShop\Module\ProductVideoLoops\CQRS\CommandHandler\DeleteProductVideoCommandHandler:
        class: PrestaShop\Module\ProductVideoLoops\CQRS\CommandHandler\DeleteProductVideoCommandHandler
        arguments:
            - '@PrestaShop\Module\ProductVideoLoops\Service\VideoManagementService'
        tags:
            - name: tactician.handler
              command: PrestaShop\Module\ProductVideoLoops\CQRS\Command\DeleteProductVideoCommand

    PrestaShop\Module\ProductVideoLoops\CQRS\QueryHandler\GetProductVideoQueryHandler:
        class: PrestaShop\Module\ProductVideoLoops\CQRS\QueryHandler\GetProductVideoQueryHandler
        arguments:
            - '@PrestaShop\Module\ProductVideoLoops\Repository\ProductVideoRepository'

    PrestaShop\Module\ProductVideoLoops\CQRS\CommandBuilder\ProductVideoCommandsBuilder:
        class: PrestaShop\Module\ProductVideoLoops\CQRS\CommandBuilder\ProductVideoCommandsBuilder
        public: true
        autowire: true
        # This tag is important. Core product command builder finds this builder by the tag
        tags: 
            - 'core.product_command_builder'

    #Services
    PrestaShop\Module\ProductVideoLoops\Service\VideoManagementService:
        public: false
        autowire: true
        arguments:
            - '@PrestaShop\Module\ProductVideoLoops\Service\VideoUploader'
            - '@PrestaShop\Module\ProductVideoLoops\Service\VideoDeleter'
            - '@PrestaShop\Module\ProductVideoLoops\Repository\ProductVideoRepository'


    PrestaShop\Module\ProductVideoLoops\Service\VideoUploader:
        class: PrestaShop\Module\ProductVideoLoops\Service\VideoUploader
        arguments:
            - '@PrestaShop\Module\ProductVideoLoops\Repository\ProductVideoRepository'
            - '@slugger'
            - '@PrestaShop\Module\ProductVideoLoops\Service\LinkBuilderService'

    PrestaShop\Module\ProductVideoLoops\Service\VideoDeleter:
        class: PrestaShop\Module\ProductVideoLoops\Service\VideoDeleter
        arguments:
            - '@PrestaShop\Module\ProductVideoLoops\Repository\ProductVideoRepository'
            - '@PrestaShop\Module\ProductVideoLoops\Service\LinkBuilderService'

    PrestaShop\Module\ProductVideoLoops\Service\ProductVideoPreviewService:
        class: PrestaShop\Module\ProductVideoLoops\Service\ProductVideoPreviewService
        public: true
        autowire: true
        arguments:
            - '@PrestaShop\Module\ProductVideoLoops\Factory\ProductVideoFactory'
            - '@PrestaShop\Module\ProductVideoLoops\Service\LinkBuilderService'

    PrestaShop\Module\ProductVideoLoops\Service\LinkBuilderService:
        class: PrestaShop\Module\ProductVideoLoops\Service\LinkBuilderService
        autowire: true

    PrestaShop\Module\ProductVideoLoops\Repository\ProductVideoRepository:
        class: PrestaShop\Module\ProductVideoLoops\Repository\ProductVideoRepository
        public: true
        autowire: true

    PrestaShop\Module\ProductVideoLoops\Factory\ProductVideoFactory:
        class: PrestaShop\Module\ProductVideoLoops\Factory\ProductVideoFactory
        public: true
        autowire: true

    PrestaShop\Module\ProductVideoLoops\Form\Type\VideoCompoundType:
        class: PrestaShop\Module\ProductVideoLoops\Form\Type\VideoCompoundType
        autowire: true
        tags:
            - { name: form.type }

    Prestashop\Module\ProductVideoLoops\Form\Theme\VideoCompound:
        class: Symfony\Component\Form\FormRendererEngineInterface
        tags:
            - { name: twig.form.theme, template: '@Modules/productvideoloops/views/templates/admin/forms/video_compound.html.twig' }

    PrestaShop\Module\ProductVideoLoops\Controller\DeleteVideoController:
        class: PrestaShop\Module\ProductVideoLoops\Controller\DeleteVideoController
        public: true
        autowire: true

    #Subscribers
    PrestaShop\Module\ProductVideoLoops\Subscriber\PresentProductHookSubscriber:
        class: PrestaShop\Module\ProductVideoLoops\Subscriber\PresentProductHookSubscriber
        public: false
        autowire: true
        arguments: 
            - '@PrestaShop\Module\ProductVideoLoops\CQRS\QueryHandler\GetProductVideoQueryHandler'
            - '@PrestaShop\Module\ProductVideoLoops\Service\LinkBuilderService'

    PrestaShop\Module\ProductVideoLoops\Subscriber\ProductsListingHookSubscriber:
        class: PrestaShop\Module\ProductVideoLoops\Subscriber\ProductsListingHookSubscriber
        public: false
        autowire: true
        arguments: 
            - '@PrestaShop\Module\ProductVideoLoops\CQRS\QueryHandler\GetProductVideoQueryHandler'
            - '@PrestaShop\Module\ProductVideoLoops\Service\LinkBuilderService'